---
title: Darwin Free University (Test Edit)
timezone: Australia/Darwin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: dfutechnical@gmail.com
description: Website for Darwin Free University, a community initiative.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
- jekyll-feed
